{% set name = "scriv" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8873d44d12fc4ad16b77eb893d5b28de13b27f22c6fd6cfaade9d7c539fa0b19

build:
  entry_points:
    - scriv = scriv.cli:cli
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - attrs
    - click
    - click-log
    - jinja2
    - markdown-it-py
    - requests

test:
  imports:
    - scriv
  commands:
    - pip check
    - scriv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nedbat/scriv
  summary: Scriv changelog management tool
  description: |
    Scriv is a command-line tool for helping developers maintain useful changelogs.
    It manages a directory of changelog fragments. It aggregates them into entries
    in a CHANGELOG file.
  dev_url: https://github.com/nedbat/scriv
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sdebionne
